name: LSIF

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Generate LSIF
        run: npm run lsif
      - name: Publish LSIF
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: lsif-index
          FOLDER: lsif_index
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
